# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: get changed files
        id: change-files
        uses: tj-actions/changed-files@v44
        with:
          files: | 
            *.py


