# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v32
      - name: List all added files
        run: |
         for file in ${{steps.changed-files.outputs.all_changed_files}}; do
          echo "$file was modified."
         done


